---
title: "machine learning demo"
author: "Mark Hancharik"
date: "10/21/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## https://machinelearningmastery.com/machine-learning-in-r-step-by-step/
```{r}

library(caret)

# define the filename
filename <- "characters.csv"
# load the CSV file from the local directory
dataset <- read.csv(filename, header=FALSE)
# set the column names in the dataset
colnames(dataset) <-  c("strength", "dexterity", "speed" ,"intelligence","charisma","constitution","Class")

# create a list of 80% of the rows in the original dataset we can use for training
validation_index <- createDataPartition(dataset$Class, p=0.50, list=FALSE)
# select 20% of the data for validation
validation <- dataset[-validation_index,]
# use the remaining 80% of data to training and testing the models
dataset <- dataset[validation_index,]

# dimensions of dataset
dim(dataset)

# list types for each attribute
sapply(dataset, class)

# take a peek at the first 5 rows of the data
head(dataset)

# list the levels for the class
levels(dataset$Class)

# summarize the class distribution
percentage <- prop.table(table(dataset$Class)) * 100
cbind(freq=table(dataset$Class), percentage=percentage)

# summarize attribute distributions
summary(dataset)

# split input and output
x <- dataset[,1:6]
y <- dataset[,7]

# boxplot for each attribute on one image
par(mfrow=c(1,6))
  for(i in 1:6) {
  boxplot(x[,i], main=names(dataset)[i])
  }


# barplot for class breakdown
#plot(y)


# scatterplot matrix
featurePlot(x, y, plot="ellipse")
# box and whisker plots for each attribute
featurePlot(x=x, y=y, plot="box")


# density plots for each attribute by class value
scales <- list(x=list(relation="free"), y=list(relation="free"))
featurePlot(x=x, y=y, plot="density", scales=scales)

# Run algorithms using 10-fold cross validation
control <- trainControl(method="cv", number=10)
metric <- "Accuracy"

# a) linear algorithms
set.seed(7)
fit.lda <- train(Class~., data=dataset, method="lda", metric=metric, trControl=control)
# b) nonlinear algorithms
# CART
set.seed(7)
fit.cart <- train(Class~., data=dataset, method="rpart", metric=metric, trControl=control)
# kNN
set.seed(7)
fit.knn <- train(Class~., data=dataset, method="knn", metric=metric, trControl=control)
# c) advanced algorithms
# SVM
set.seed(7)
fit.svm <- train(Class~., data=dataset, method="svmRadial", metric=metric, trControl=control)
# Random Forest
set.seed(7)
fit.rf <- train(Class~., data=dataset, method="rf", metric=metric, trControl=control)

# attempt to save model
saveRDS(fit.rf, "./character_class_model_rf.rds")
saveRDS(fit.lda, "./character_class_model_lda.rds")

# summarize accuracy of models
results <- resamples(list(lda=fit.lda, cart=fit.cart, knn=fit.knn, svm=fit.svm, rf=fit.rf))
summary(results)



# compare accuracy of models
dotplot(results)



# summarize Best Model
print(fit.lda)


# estimate skill of LDA on the validation dataset
predictions <- predict(fit.lda, validation)
confusionMatrix(predictions, validation$Class)



```